### ISSUE TITLE
网页好像无法正常渲染

### ISSUE THREAD

**Issue by garviezhao** [dxs1256/jxvip#1]
你好，我下载你的到本地打开之后出现的网页似乎无法正常渲染。
我把图片上传到了图床，你请看看。
https://imgchr.com/i/3L0w8J
[https://imgchr.com/i/3L0w8J](url)

**Comment by dxs1256** [comment]
我在本地也无法正常渲染，我是直接放在GitHub上是正常的。我也不是作者，我还是个小白

在 2020-03-06 20:29:56，"garviezhao" <notifications@github.com> 写道：

你好，我下载你的到本地打开之后出现的网页似乎无法正常渲染。
我把图片上传到了图床，你请看看。
https://imgchr.com/i/3L0w8J
https://imgchr.com/i/3L0w8J

**Comment by garviezhao** [comment]
> 我在本地也无法正常渲染，我是直接放在GitHub上是正常的。我也不是作者，我还是个小白 在 2020-03-06 20:29:56，"garviezhao" <notifications@github.com> 写道： 你好，我下载你的到本地打开之后出现的网页似乎无法正常渲染。 我把图片上传到了图床，你请看看。 https://imgchr.com/i/3L0w8J https://imgchr.com/i/3L0w8J — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，谢谢了
